name = "rgi-tnp"
main = ".open-next/worker.js"
compatibility_date = "2026-06-13"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "rgi-tnp"

[[d1_databases]]
binding = "DB"
database_name = "placement-db"
database_id = "ce5c387a-ca67-4ff6-aca0-7ff20892695b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "placement-assets"
