name = "rgi-tnp"
main = ".open-next/worker.js"
compatibility_date = "2026-06-05"
compatibility_flags = ["nodejs_compat", "global_fetch_strictly_public"]

[assets]
directory = ".open-next/assets"
binding = "ASSETS"

[observability]
enabled = true

[[services]]
binding = "WORKER_SELF_REFERENCE"
service = "rgi-tnp"

[[d1_databases]]
binding = "DB"
database_name = "placement-db"
database_id = "ce5c387a-ca67-4ff6-aca0-7ff20892695b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "placement-assets"

[[kv_namespaces]]
binding = "IMAGES"
id = "2cfdb84a0d6d42bdbc3b14a2285ebbf6"

[vars]
R2_BUCKET_NAME = "placement-assets"
R2_END_POINT = "https://f1367f64dbf752b13589fe0e999e885b.r2.cloudflarestorage.com"
R2_PUBLIC_URL = "https://pub-1b5e6b5b4fbe4c89940f9bb74b08fa75.r2.dev"
EMAIL_FROM = "ankit@ankitdevprojects.qzz.io"
GMAIL_USER = "ankit.education86@gmail.com"
ADMIN_EMAIL = "admin@rgi.ac.in"
DOMAIN_NAME = "ankit-dev.me"

