name = "rgi-tnp"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[[d1_databases]]
binding = "DB"
database_name = "placement-db"
database_id = "ce5c387a-ca67-4ff6-aca0-7ff20892695b"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "placement-assets"