-- Migration: Add isApproved and timestamps to StudentFeedback table
-- NOTE: Columns already exist in database - this is a no-op migration to mark as applied
-- The columns were created in a previous migration run
