-- Migration: Add email verification failure tracking columns
-- NOTE: Columns already exist in database - this is a no-op migration to mark as applied
-- The columns were created in previous migration runs
