-- Add missing isProfileComplete column to Student table
-- This column was lost during the schema sync in migration 0007
-- Note: Column already exists, so this migration is skipped
-- SQLite doesn't support IF NOT EXISTS on ADD COLUMN, so we use a workaround
